config/routes.rb
Rails.application.routes.draw do
  get 'retweets/create'
  get 'retweets/destroy'

  get 'likes/create'
  get 'likes/destroy'

  get 'password_resets/new'
  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate :picture_size

  has_many :likes, dependent: :destroy
  has_many :retweets, dependent: :destroy

  # いいねしたかしてないかを確認する
  def like_user(user_id)
    self.likes.find_by(user_id: user_id)
  end

  # シェア=リツイートしたかしてないか確認する
  def retweet_user(user_id)
    self.retweets.find_by(user_id: user_id)
  end

  # リツイートした人を返す
  def retweet_users
    u = User.where(id: self.retweets.pluck(:user_id)).pluck(:name)
    if u && u.count > 2
      "#{u.first}と#{u.second}さん他#{u.count - 2}さんがリツイートしました。"
    else
      "#{u.join("と")}さんがリツイートしました。"
    end
  end

  # ユーザーのあいまい検索
  def self.search(search)
    if search
      where('content LIKE ?', "%#{search}%")
    else
      all
    end
  end

private

  # アップロードされた画像のサイズをバリデーションする
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_parms)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  private

    def micropost_parms
      params.require(:micropost).permit(:content, :picture)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?


    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_hart.html.erb
<% if micropost.like_user(current_user.id) %>
  <%= link_to fa_icon("heart red", text: micropost.likes_count), likes_destroy_path(micropost_id: micropost.id), remote: true, class: "micropost#{micropost.id}" %>
<% else %>
  <%= link_to fa_icon("heart-o", text: micropost.likes_count), likes_create_path(micropost_id: micropost.id), remote: true, class: "micropost#{micropost.id}"  %>
<% end %>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <% if micropost.retweets.present? %>
    <p><%= fa_icon("retweet green", text: micropost.retweet_users) %></p>
  <% end %>
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <span class="action">
    <span id="like">
      <%= render "microposts/hart", micropost: micropost %>
    </span>
    <% if micropost.retweet_user(current_user) %>
      <%= link_to fa_icon("retweet green", text: micropost.retweets.count), retweets_destroy_path(micropost_id: micropost.id) %>
    <% else %>
      <%= link_to fa_icon("retweet", text: micropost.retweets.count), retweets_create_path(micropost_id: micropost.id) %>
    <% end %>
    <% if current_user?(micropost.user) %>
      <%= link_to fa_icon("trash"), micropost, method: :delete, data: {confirm: "You sure?"}, micropost_id: micropost.id  %>
    <% end %>
  </span>
</li>

app/views/microposts/_show_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <% if micropost.retweets.present? && micropost.retweet_user(current_user) %>
    <p><%= fa_icon("retweet green", text: "自分がリツイート") %></p>
  <% end %>
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <span class="action">
    <span id="like">
      <%= render "microposts/hart", micropost: micropost %>
    </span>
    <% if micropost.retweet_user(current_user) %>
      <%= link_to fa_icon("retweet green", text: micropost.retweets.count), retweets_destroy_path(micropost_id: micropost.id) %>
    <% else %>
      <%= link_to fa_icon("retweet", text: micropost.retweets.count), retweets_create_path(micropost_id: micropost.id) %>
    <% end %>
    <% if current_user?(micropost.user) %>
      <%= link_to fa_icon("trash"), micropost, method: :delete, data: {confirm: "You sure?"}, micropost_id: micropost.id  %>
    <% end %>
  </span>
</li>